import Head from "next/head";
import { useRouter } from "next/router";
import styles from "@/styles/Home.module.css";
import HomePage from "./home";
import withSession from "./api/session";
import AddCircleIcon from '@mui/icons-material/AddCircle';

export default function Home({ user }) {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage user={user} />

      <div className={styles.container}>
        {user && user?.email === process.env.NEXT_PUBLIC_ADMIN_EMAIL || user && user?.email === process.env.NEXT_PUBLIC_ADMIN_EMAIL2 && (
          <div className={styles.addContainer}>
            <AddCircleIcon className={styles.icon} onClick={() => router.push("/my-product")} />
          </div>
        )}

      </div>
    </>
  );
}

export const getServerSideProps = withSession(async function ({ req, res }) {
  const user = req.session.get("user");
  const currentPath = req ? req.url : window.location.pathname;

  if (user) {
    req.session.set("user", user);
    await req.session.save();
  }

  return {
    props: {
      user: user ? user : null,
    },
  };
});
